#!/usr/bin/env python

# Reformat from gajim's exported format to sxc.

import sys
import re

def main(argv=None):
  if not argv:
    argv = sys.argv

  if len(argv) != 2:
    print >> sys.stderr, "Usage: " + argv[0] + " jid"
    sys.exit(1)

  myjid = argv[1]
  length = 0

  while True:
    line = sys.stdin.readline()
    if not line:
      break

    if re.match("^You on [0-9][0-9]/[0-9][0-9]/[0-9][0-9][0-9][0-9] said: ", line):
      text = re.sub("^You on ([0-9][0-9])/([0-9][0-9])/([0-9][0-9][0-9][0-9]) said: ", r"\3-\1-\2T00:00:00 <" + myjid + "> ", line[:-1])
      length = len(text.split(">")[0]) + 2

    elif re.match("^[^ ]*@[^ ]* on [0-9][0-9]/[0-9][0-9]/[0-9][0-9][0-9][0-9] said: ", line):
      text = re.sub("^(.*) on ([0-9][0-9])/([0-9][0-9])/([0-9][0-9][0-9][0-9]) said: ", r"\4-\2-\3T00:00:00 <\1> ", line[:-1])
      length = len(text.split(">")[0]) + 2

    else:
      text = length * " " + line[:-1]

    print text


if __name__ == '__main__':
  main()
