#!/bin/sh

cd $1
DIR=`find * -depth -iname "*$2*" | head -n1`
TITLE=`echo $DIR | sed -e "s#.*/##"`

[ "$DIR" ] || exit

cd $DIR
echo -en "\033]2;$TITLE\007"
splitvt -norc -upper sxc-tail -lower sxc-vim -bottom -s 100
